package beans;
// Generated 24-Jan-2019 17:29:26 by Hibernate Tools 4.3.1

/**
 * Auth generated by hbm2java
 */
public class Auth implements java.io.Serializable {

    private String username;
    private UserAcc userAcc;
    private String password;

    public Auth() {
    }

    public Auth(String username, UserAcc userAcc, String password) {
        this.username = username;
        this.userAcc = userAcc;
        this.password = password;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public UserAcc getUserAcc() {
        return this.userAcc;
    }

    public void setUserAcc(UserAcc userAcc) {
        this.userAcc = userAcc;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
