package beans;
// Generated 24-Jan-2019 17:29:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserAcc generated by hbm2java
 */
public class UserAcc  implements java.io.Serializable {


     private Integer id;
     private String team;
     private String name;
     private int type;
     private boolean approved;
     private Set auths = new HashSet(0);
     private Set teammateses = new HashSet(0);

    public UserAcc() {
    }

	
    public UserAcc(String name, int type, boolean approved) {
        this.name = name;
        this.type = type;
        this.approved = approved;
    }
    public UserAcc(String team, String name, int type, boolean approved, Set auths, Set teammateses) {
       this.team = team;
       this.name = name;
       this.type = type;
       this.approved = approved;
       this.auths = auths;
       this.teammateses = teammateses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public boolean isApproved() {
        return this.approved;
    }
    
    public void setApproved(boolean approved) {
        this.approved = approved;
    }
    public Set getAuths() {
        return this.auths;
    }
    
    public void setAuths(Set auths) {
        this.auths = auths;
    }
    public Set getTeammateses() {
        return this.teammateses;
    }
    
    public void setTeammateses(Set teammateses) {
        this.teammateses = teammateses;
    }




}


